version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies (binutils-gdb)
          command: |
            apt update
            apt install -y bison flex texinfo git build-essential
      - run:
          name: Clone (binutils-gdb)
          command: |
            git clone https://github.com/stephenrkell/binutils-gdb.git ~/binutils-gdb
      - run:
          name: Configure, build, install (binutils-gdb)
          working_directory: ~/binutils-gdb
          command: |
            chmod +x configure
            CFLAGS="-fPIC -g -O2" ./configure --prefix=/usr/local \
              --enable-gold --enable-plugins --enable-install-libiberty
            make -j 2 all-binutils all-gold all-libiberty
            make install-binutils install-gold install-libiberty
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              libelf-dev libdw-dev binutils-dev \
              autoconf automake libtool pkg-config autoconf-archive \
              g++ ocaml ocamlbuild ocaml-findlib \
              default-jdk-headless python3 python \
              make git gawk gdb wget \
              libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
              libboost-iostreams-dev libboost-regex-dev \
              libboost-serialization-dev libboost-filesystem-dev
      - run:
          name: Report OCaml version for debugging
          command: |
            dpkg -l | grep ocaml
      - checkout
      - run:
          name: Update submodules
          command: git submodule update --init --recursive
      - run:
          name: Build submodules
          command: make -C contrib -j 2
      - run:
          name: Build project
          command: |
            . contrib/env.sh
            ./autogen.sh
            ./configure
            make -j 2
      - run:
          name: Create liballocs metadata
          command: |
            mkdir -p /usr/lib/meta
            make -f tools/Makefile.meta /usr/lib/meta`ldd /bin/true | grep 'libc.so.6' | sed -r 's/.*=> (.*) \(.*/\1/' | xargs readlink -f`-meta.so
      - persist_to_workspace:
          root: /root
          paths: project binutils-gdb
  test:
    requires:
      - build
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y ca-certificates make build-essential g++ autoconf automake libtool \
              libelf-dev python3 python git gawk python3-distutils libunwind-dev \
              ocaml ocamlbuild ocaml-findlib \
              libdw-dev \
              libboost-iostreams-dev libboost-regex-dev \
              libboost-serialization-dev libboost-filesystem-dev
      - attach_workspace:
          at: /root
      - run:
          name: Re-install binutils-gdb to override system binutils
          working_directory: ~/binutils-gdb
          command: |
            make install-binutils install-gold install-libiberty
      - run:
          name: Report OCaml version for debugging
          command: |
            dpkg -l | grep ocaml
      - run:
          name: Run tests
          command: make -C /root/project/tests -j 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
